name: service-workflow
on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'github-actions-pipeline'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v5
          with:
            go-version: 1.22.5
        run: go get
      - name: Go build
        run: go build -v ./...
      - name: Go test 
        run: go test -v ./...
        # release:
        #   runs-on: ubuntu-22.04
        #   steps:
        #     - name: Checkout
        #       uses: actions/checkout@v4
        #     - name: Login to docker hub
        #       uses: docker/login-action@v3
        #       with:
        #         username: $
        #         password: $
        #     - name: Set up docker buildx
        #       uses: docker/setup-buildx-action@v3
        #     - name: Build and push
        #       uses: docker/build-push-action@v6
        #       with:
        #         context: .
        #         file: ./Dockerfile
        #         push: true
        #         tags: $/home_mgmt_service:latest
